### ISSUE TITLE
error compiling with VStudio 2015 update 2

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-mysql#19]
Hi Roland,

The code

``` C++
auto prepared_update = db.prepare(
        update(tab)
        .set(tab.colDayPoint = parameter(tab.colDayPoint)).unconditionally());
```

gives this compiler error:

```
**error C2440: 'static_cast': cannot convert from 
'const sqlpp::parameter_list_t<sqlpp::detail::type_vector<sqlpp::parameter_t<sqlpp::day_point,T>>>' 
to 
'TabDateTime_::ColDayPoint::_alias_t::_member_t<sqlpp::parameter_value_t<sqlpp::day_point>> &'
          with
          [
              T=sqlpp::column_t<TabDateTime,TabDateTime_::ColDayPoint>
          ]**
```

I have no idea why this is happening ...

Do you?

Regards,
Juan

**Comment by rbock** [comment]
Not yet. Do any of these sub statements compile?

```
tab.colDayPoint = parameter(tab.colDayPoint;

update(tab)..set(tab.colDayPoint = parameter(tab.colDayPoint);
```

**Comment by juandent** [comment]
Yes, these compile fine:

``` C++
tab.colDayPoint = parameter(tab.colDayPoint);

update(tab).set(tab.colDayPoint = parameter(tab.colDayPoint));
```

**Comment by juandent** [comment]
Hi Roland,

Actually there is more that may help you: if I remove the `unconditionally()` like so:

``` C++
    auto prepared_update = db.prepare(
        update(tab)
        .set(tab.colDayPoint = parameter(tab.colDayPoint)));           // .unconditionally());
```

I get a worst error:
**error C3313: 'prepared_update': variable cannot have the type 'void'**

**Comment by rbock** [comment]
Hi Juan,

Thanks. I assume that is not the complete error message though, is it? There should be some output from a static_assert, too.

Anyway, please try again with the current sqlpp11 develop branch. I am pretty sure I fixed your original query.

Best,

Roland

**Comment by juandent** [comment]
Hi Roland,

No, there is no more error output from any static_assert. I tried with the current sqlpp11 develop branch to no avail.

I tried something that removed all compile errors, but I have a feeling this does not solve the problem (probably a "false" fix - please check it to see if it makes semantics sense).

It has to do with removing an & in the static_cast in line 65 of parameter_list.h like so:

``` C++
    template <typename Target, size_t... Is>
    void _bind_impl(Target& target, const detail::index_sequence<Is...>&) const
    {
      using swallow = int[];  // see interpret_tuple.h
      (void)swallow{0, (
          static_cast<typename std::tuple_element<Is, const _member_tuple_t>::type/*&*/>(*this)()._bind(target, Is), 0)...};
    }
```

This code throws an exception:

``` C++
    auto prepared_update = db.prepare(
        update(tab)
            .set(tab.colDayPoint = parameter(tab.colDayPoint), tab.colTimePoint = parameter(tab.colTimePoint))
            .unconditionally());

    prepared_update.params.colDayPoint = today;
    prepared_update.params.colTimePoint = now;
    std::cout << "---- running prepared update ----" << std::endl;
    db(prepared_update);
    std::cout << "---- finished prepared update ----" << std::endl;
    for (const auto& row : db(select(all_of(tab)).from(tab).unconditionally()))
    {
      require_equal(__LINE__, row.colDayPoint.value(), today);
      require_equal(__LINE__, row.colTimePoint.value(), now);
    }
  }
  catch (const std::exception& e)
  {
    std::cerr << "Exception: " << e.what() << std::endl;
    return 1;
  }

```

the output is:

**---- running prepared update ----
MySQL debug: binding date parameter  at index: 0, being not null
MySQL debug: binding date_time parameter  at index: 1, being not null
MySQL debug: Executing prepared_statement
Exception: MySQL error: Could not execute prepared statement: Incorrect date value: '' for column 'col_day_point' at row 1**

So, something is fishy with the prepared statement....

Regards,
Juan

**Comment by rbock** [comment]
Your 'fix' leads to parameter values not being set.

Please try again with the latest develop version of sqlpp11. I fixed the problem. It compiles on appveyor with MSVC 2015 Update 2. There is a problem with the linker now, but that is a problem of the setup on appveyor.

Best,

Roland

**Comment by rbock** [comment]
I am testing appveyor on this branch here: feature/appveyor_integration

**Comment by juandent** [comment]
Yes Roland with latest sqlpp11 from develop branch it now compiles without errors BUT the behavior is as before -- the parameter values are not being set for the prepared update as we can see in the output:

**---- running prepared update ----
MySQL debug: binding date parameter  at index: 0, being not null
MySQL debug: binding date_time parameter  at index: 1, being not null
MySQL debug: Executing prepared_statement
Exception: MySQL error: Could not execute prepared statement: Incorrect date value: '' for column 'col_day_point' at row 1**

What could be going on? I am not that familiar yet with your code ... I have been taking time out but nothing too committed.

Regards,
Juan

**Comment by rbock** [comment]
BTW, I just confirmed the compile error you reported if you omit the `unconditionally()`. It is so annoying that compilers behave so differently. Every other compiler reports a static_assert...

Since I cannot run the tests on appveyor yet, in file `src/prepared_statement.cpp`, functions `_bind_date_parameter` and `_bind_date_time_parameter` can you please add this line:

```
std::cerr << "bound values: " << bound_time.year << '-' << bound_time.month << '-' << bound_time.day << 'T' << bound_time.hour << ':' << bound_time.minute << ':' << bound_time.second << std::endl;
```

at the end of the `if (not is_null)` block.

Thanks,

Roland

**Comment by juandent** [comment]
Hi Roland,
I just had the chance to add the code you asked me and when I execute the prepared update I get this error message:
**---- running prepared update ----
MySQL debug: binding date parameter  at index: 0, being not null
bound values: 2016-5-15T0:0:0
MySQL debug: binding date_time parameter  at index: 1, being not null
bound values: 2016-5-15T3:5:27
MySQL debug: Executing prepared_statement
Exception: MySQL error: Could not execute prepared statement: Incorrect date value: '' for column 'col_day_point' at row 1**

So is this bit more of information helpful?

Regards,
Juan

**Comment by rbock** [comment]
Hi Juan,

Thanks for testing. It is very helpful in that it assures that reasonable values were used.

Yikes! I think I just found the bug. Thought I fixed that long ago...

Please try again with the current develop of sqlpp11-connector-mysql

Best,

Roland

**Comment by juandent** [comment]
Hi Roland,

Just tried it: it works!!!  Congratulations :-)

Regards,
Juan

**Comment by rbock** [comment]
Hi Juan,

cool, thanks for the support!

Best,

Roland
